#! /bin/sh /usr/share/dpatch/dpatch-run
## apps_Makefile.dpatch by Jose Carlos Garcia Sogo <jsogo@debian.org>
##
## All lines beginning with `## DP:' are a description of the patch.
## DP: No description.

@DPATCH@
diff -urNad asterisk-1.0.2/apps/Makefile /tmp/dpep.BrtuIJ/asterisk-1.0.2/apps/Makefile
--- asterisk-1.0.2/apps/Makefile	2004-09-24 23:32:56.000000000 +0200
+++ /tmp/dpep.BrtuIJ/asterisk-1.0.2/apps/Makefile	2005-01-04 21:09:20.000000000 +0100
@@ -35,7 +35,7 @@
 APPS+=app_intercom.so
 endif
 
-#APPS+=app_sql_postgres.so
+APPS+=app_sql_postgres.so
 #APPS+=app_sql_odbc.so
 #APPS+=app_rpt.so
 
@@ -89,7 +89,7 @@
 	$(CC) $(SOLINK) -o $@ $< -lodbc
 
 look:	look.c
-	$(CC) -pipe -O6 -g look.c -o look -lncurses
+	$(CC) -pipe -g look.c -o look -lncurses
 
 ifneq ($(wildcard .depend),)
 include .depend
diff -urNad asterisk-1.0.2/cdr/Makefile /tmp/dpep.gih1QV/asterisk-1.0.2/cdr/Makefile
--- asterisk-1.0.2/cdr/Makefile	2004-08-31 18:33:00.000000000 +0200
+++ /tmp/dpep.gih1QV/asterisk-1.0.2/cdr/Makefile	2005-01-04 21:26:19.000000000 +0100
@@ -12,7 +12,7 @@
 #
 
 #ADD cdr_pgsql.so to MODS= to include PostgreSQL support: REQUIRES PostgreSQL libs
-MODS=cdr_csv.so cdr_manager.so
+MODS=cdr_csv.so cdr_manager.so cdr_pgsql.so
 
 
 CFLAGS+=-fPIC
diff -urNad asterisk-1.0.2/codecs/lpc10/Makefile /tmp/dpep.jsjL9g/asterisk-1.0.2/codecs/lpc10/Makefile
--- asterisk-1.0.2/codecs/lpc10/Makefile	2004-08-31 18:33:00.000000000 +0200
+++ /tmp/dpep.jsjL9g/asterisk-1.0.2/codecs/lpc10/Makefile	2005-01-04 21:36:33.000000000 +0100
@@ -39,7 +39,7 @@
 ifeq ($(PROC),ultrasparc)
         CFLAGS+= -mtune=$(PROC) -mcpu=v8 -O3 -fomit-frame-pointer
 else
-        CFLAGS+= -march=$(PROC)
+	CFLAGS+=$(shell if $(CC) -march=$(PROC) -S -o /dev/null -xc /dev/null >/dev/null 2>&1; then echo "-march=$(PROC)"; fi)
 endif
 endif
 endif
@@ -47,7 +47,7 @@
 endif
 endif
 
-LIB = $(LIB_TARGET_DIR)/liblpc10.a
+LIB = ./liblpc10.a
 
 .PHONY: all clean
 
