#! /bin/sh -e

if [ "$1" = "configure" ]; then

    ## Special magick to upgrade from versions 1:1.2.14~dfsg-1 and earlier
    ## Can be removed after release of lenny
    SRC=/usr/share/asterisk/sounds/priv-callerintros
    DST=/var/lib/asterisk/sounds/priv-callerintros
    if [ -d "${SRC}" ] && [ ! -h "${SRC}" ]; then
	# We need to move the callerintros directory to /var/lib
	# this is supposed to work also if $DST already exists.
	# (this must be the case as per policy § 6.2)
	mkdir -p "${DST}"
	# This overwrites files with the same name in $DST. This is
	# done on purpose, as the ones in $SRC are the ones actually
	# used by asterisk.
	find "${SRC}" -mindepth 1 -maxdepth 1 -print0 | xargs -s 1024 -n 100 --null mv --target-directory="${DST}"
	rmdir "${SRC}"
    fi
    if [ ! -h "${SRC}" ]; then
        ln -s "${DST}" "${SRC}"
    fi
    ## End special magick to upgrade

fi