#!/bin/bash
#
# Hook for automatic backports at buildserver.net
#
# Target dist: Ubuntu Dapper

# Use old dpkg syntax (which was not binNMU-safe)
sed -i -e 's#^\(Build-Depends:.*\)dpkg[^,$]*[\ ,$]\+\(.*\)$#\1\2#' -e 's#${source:Version})#${Source-Version})#g' debian/control

exit 0
