#!/bin/bash
#
# Hook for automatic backports at Buildserver.NET
#
# Target dist: Ubuntu Dapper

# Replace libcurl4-openssl-dev with libcurl3-dev
sed -i -e 's#^\(Build-Depends:.*\)libcurl4[^\ ]*-dev[^\ ]* \(.*\)$#\1libcurl3-dev \2#' debian/control

# Replace libsnmp10-dev with libsnmp9-dev
sed -i -e 's#^\(Build-Depends:.*\)libsnmp10-dev[^\ ]* \(.*\)$#\1libsnmp9-dev \2#' debian/control

# Undo binary:Version and source:Version
sed -i -e 's#binary:Version#Source-Version#g' \
  -e 's#binary:Version#Source-Version#g' \
  -e 's#^\(Build-Depends:.*\),\ *dpkg-dev ([^)]*)\(.*\)$#\1\2#' \
  debian/control

exit 0
