#!/bin/bash
#
# Hook for automatic backports at Buildserver.NET
#
# Target dist: Ubuntu Edgy

# Replace libcurl4-openssl-dev with libcurl3-dev
sed -i -e 's#^ libcurl4.*-dev,$/# libcurl3-dev#' debian/control

# Replace libsnmp-dev with libsnmp9-dev
sed -i -e 's#^ libsnmp-dev.*,$# libsnmp9-dev#' debian/control

# remove vpb-driver dependency
sed -i -e '/^ libvpb-dev/d' debian/control

echo >&2 "Changes in control file were not tested. Remove these lines"
echo >&2 "once the script is tested."
exit 1

exit 0
