#!/bin/sh
#
# Backport current Asterisk to  (Etch + pkg-voip packages):

# Replace libcurl4-openssl-dev with libcurl3-dev
sed -i -e 's#^ libcurl4.*-dev# libcurl3-dev#' debian/control

# Replace libsnmp-dev with libsnmp9-dev
sed -i -e 's#^ libsnmp-dev# libsnmp9-dev#' debian/control

# remove vpb-driver dependency
sed -i -e '/^ libvpb-dev/d' debian/control

# Until we can have a stable backport of the new speex, let's just use 
# our existing "broken" speex 1.1.12:
sed -i -e '/^ libspeexdsp-dev/d' debian/control

# dh_lintian is new
sed -i -e '/dh_lintian/d' debian/rules
sed -i -e 's#^ debhelper (>= [0-9\.]*),# debhelper (>= 5),#' debian/control

# Remove explicit imap support:
sed -i -e '/^ libc-client2007b-dev/d' debian/control
sed -i -e 's/--with-imap=system/--without-imap/' debian/rules

# Remove the OSP ToolKit (app_osplookup)
sed -i -e '/^ libosptk3-dev/d' debian/control

# Remove AIS support (res_ais)
sed -i -e '/^ libopenais-dev/d' debian/control

# Remove Jack (app_jack)
sed -i -e '/^ libjack-dev/d' debian/control

exit 0
