#!/bin/bash
#
# Hook for automatic backports at Buildserver.NET
#
# Target dist: Debian Sarge

# back then libpq-dev was postgresql-dev
sed -i -e 's#^\(Build-Depends:.*)libpq-dev[^\ ,]#\1postgresql-dev#' debian/control

# Replace libcurl4-openssl-dev with libcurl3-dev
sed -i -e 's#^\(Build-Depends:.*\)libcurl4-openssl-dev[^\ ]* \(.*\)$#\1libcurl3-dev \2#' debian/control

# Replace libsnmp10-dev with libsnmp9-dev
sed -i -e 's#^\(Build-Depends:.*\)libsnmp10-dev[^\ ]* \(.*\)$#\1libsnmp9-dev \2#' debian/control

# Ditch libc-client2006j2-dev
sed -i -e 's#[, ]*libc-client2006j2-dev##' debian/control
sed -i -e '/--with-imap/d' -e '/\(sed.*MENUSELECT_OPTS_app_voicemail.*IMAP_STORAGE.*menuselect.makeopts\)/#\1' debian/rules

# Undo binary:Version and source:Version
sed -i -e 's#binary:Version#Source-Version#g' \
  -e 's#binary:Version#Source-Version#g' \
  -e 's#^\(Build-Depends:.*\),\ *dpkg-dev ([^)]*)\(.*\)$#\1\2#' \
  debian/control

exit 0
